// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3K87Q7ZKA57hLn5o0jhih7KJ_vTlDgeQ',
    appId: '1:94689171996:web:5525412baa6c286dec5dd9',
    messagingSenderId: '94689171996',
    projectId: 'communityapp-67cba',
    authDomain: 'communityapp-67cba.firebaseapp.com',
    storageBucket: 'communityapp-67cba.firebasestorage.app',
    measurementId: 'G-2RV28PFZFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsovVvo3tMIHcceuoeWz-Zf6i83bNR1GM',
    appId: '1:94689171996:android:34a375b236fdb42eec5dd9',
    messagingSenderId: '94689171996',
    projectId: 'communityapp-67cba',
    storageBucket: 'communityapp-67cba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARjwS4kbh770FkAMYIt_InM9SuQb-A80E',
    appId: '1:94689171996:ios:ed5c9e32dac946fbec5dd9',
    messagingSenderId: '94689171996',
    projectId: 'communityapp-67cba',
    storageBucket: 'communityapp-67cba.firebasestorage.app',
    iosBundleId: 'com.example.rakhsa.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARjwS4kbh770FkAMYIt_InM9SuQb-A80E',
    appId: '1:94689171996:ios:cd9cb4d4ec174904ec5dd9',
    messagingSenderId: '94689171996',
    projectId: 'communityapp-67cba',
    storageBucket: 'communityapp-67cba.firebasestorage.app',
    iosBundleId: 'com.example.rakhsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3K87Q7ZKA57hLn5o0jhih7KJ_vTlDgeQ',
    appId: '1:94689171996:web:2d1497a5d0bbe5d2ec5dd9',
    messagingSenderId: '94689171996',
    projectId: 'communityapp-67cba',
    authDomain: 'communityapp-67cba.firebaseapp.com',
    storageBucket: 'communityapp-67cba.firebasestorage.app',
    measurementId: 'G-4JY4GR0D4D',
  );
}
